### ISSUE TITLE
DG-ID, FCS, YSF and YCS

### ISSUE THREAD

**Issue by dg9ffm** [AndyTaylorTweet/Pi-Star_v4_Binaries_Bin#4]
DG IDs are not passed on by pistar's MMDVMHost. they are still set to 00.
Please update MMDVMHost.

Please update YSFGateway to support new YCS (FCS) servers. YSF and FCS protocol now support 100 DG-ID and option parameters for the static booking of several DG-IDs when registering with a ysf or fcs reflector.
See: https://github.com/g4klx/YSFClients/tree/master/YSFGateway

**Comment by MW0MWZ** [comment]
updated
